$(document).on 'forms#new:loaded', ->
	console.log 'loaded'
	map = undefined
	infoWindow = undefined
	initMap()





initMap = ->
  map = new (google.maps.Map)(document.getElementById('map'),
    center:
      lat: -34.397
      lng: 150.644
    zoom: 6)
  infoWindow = new (google.maps.InfoWindow)
  # Try HTML5 geolocation.
  if navigator.geolocation
    navigator.geolocation.getCurrentPosition ((position) ->
      pos = 
        lat: position.coords.latitude
        lng: position.coords.longitude
      infoWindow.setPosition pos
      infoWindow.setContent 'Location found.'
      infoWindow.open map
      map.setCenter pos
      map.getCe
      console.log "http://www.google.com/maps/place/#{map.getCenter().toUrlValue()}"
      return
    ), ->
      handleLocationError true, infoWindow, map.getCenter()
      return
  else
    # Browser doesn't support Geolocation
    handleLocationError false, infoWindow, map.getCenter()
  return

handleLocationError = (browserHasGeolocation, infoWindow, pos) ->
  infoWindow.setPosition pos
  infoWindow.setContent if browserHasGeolocation then 'Error: The Geolocation service failed.' else 'Error: Your browser doesn\'t support geolocation.'
  infoWindow.open map
  return



# ---
# generated by js2coffee 2.2.0